class CSVReportService {
  constructor() {
    this.delimiter = ',';
    this.lineBreak = '\n';
  }

  generateReportCSV(reportData, reportName = 'Report') {
    const reportType = reportData.reportMetadata.reportType;
    let csvContent = '';
    
    // Add header information
    csvContent += this.generateHeader(reportData, reportName);
    csvContent += this.lineBreak + this.lineBreak;
    
    // Add summary section
    csvContent += this.generateSummarySection(reportData.data.summary);
    csvContent += this.lineBreak + this.lineBreak;
    
    // Add report-specific sections
    switch (reportType) {
      case 'registered-jobseekers':
        csvContent += this.generateJobseekerSections(reportData.data);
        break;
      case 'employers-companies':
        csvContent += this.generateEmployerSections(reportData.data);
        break;
      case 'job-postings':
        csvContent += this.generateJobPostingSections(reportData.data);
        break;
      case 'job-demand-analytics':
        csvContent += this.generateJobDemandSections(reportData.data);
        break;
    }
    
    // Add detailed data if available
    if (reportData.data.details && reportData.data.details.length > 0) {
      csvContent += this.lineBreak + this.lineBreak;
      csvContent += this.generateDetailsSection(reportData.data.details);
    }
    
    return Buffer.from(csvContent, 'utf8');
  }

  generateHeader(reportData, reportName) {
    const metadata = reportData.reportMetadata;
    let header = '';
    
    header += `"PESO - Public Employment Service Office"${this.lineBreak}`;
    header += `"${reportName}"${this.lineBreak}`;
    header += `"Generated: ${new Date(metadata.generatedAt).toLocaleString()}"${this.lineBreak}`;
    header += `"Date Range: ${metadata.startDate} to ${metadata.endDate}"${this.lineBreak}`;
    header += `"Generated By: ${metadata.generatedBy || 'System'}"${this.lineBreak}`;
    header += `"Format: CSV"${this.lineBreak}`;
    
    return header;
  }

  generateSummarySection(summary) {
    if (!summary) return '';
    
    let section = '"EXECUTIVE SUMMARY"' + this.lineBreak;
    section += '"Metric","Value"' + this.lineBreak;
    
    Object.entries(summary).forEach(([key, value]) => {
      const formattedKey = this.formatLabel(key);
      const formattedValue = this.formatValue(value);
      section += `"${formattedKey}","${formattedValue}"${this.lineBreak}`;
    });
    
    return section;
  }

  generateJobseekerSections(data) {
    let sections = '';
    
    // Demographics section
    if (data.demographics) {
      sections += this.lineBreak + '"DEMOGRAPHICS ANALYSIS"' + this.lineBreak;
      
      if (data.demographics.byGender && data.demographics.byGender.length > 0) {
        sections += this.lineBreak + '"Gender Distribution"' + this.lineBreak;
        sections += '"Gender","Count","Percentage"' + this.lineBreak;
        
        const totalGender = data.demographics.byGender.reduce((sum, item) => sum + item.count, 0);
        data.demographics.byGender.forEach(item => {
          const percentage = totalGender > 0 ? ((item.count / totalGender) * 100).toFixed(1) : 0;
          sections += `"${item._id || 'Not Specified'}","${item.count}","${percentage}%"${this.lineBreak}`;
        });
      }
      
      if (data.demographics.byAge && data.demographics.byAge.length > 0) {
        sections += this.lineBreak + '"Age Distribution"' + this.lineBreak;
        sections += '"Age Group","Count","Percentage"' + this.lineBreak;
        
        const totalAge = data.demographics.byAge.reduce((sum, item) => sum + item.count, 0);
        data.demographics.byAge.forEach(item => {
          const percentage = totalAge > 0 ? ((item.count / totalAge) * 100).toFixed(1) : 0;
          sections += `"${item._id}","${item.count}","${percentage}%"${this.lineBreak}`;
        });
      }
    }
    
    // Registration trends
    if (data.registrationTrends) {
      sections += this.lineBreak + '"REGISTRATION TRENDS"' + this.lineBreak;
      sections += '"Date","Count"' + this.lineBreak;
      
      data.registrationTrends.forEach(trend => {
        const date = this.formatTrendDate(trend._id);
        sections += `"${date}","${trend.count}"${this.lineBreak}`;
      });
    }
    
    return sections;
  }

  generateEmployerSections(data) {
    let sections = '';
    
    // Industry distribution
    if (data.industryDistribution) {
      sections += this.lineBreak + '"INDUSTRY DISTRIBUTION"' + this.lineBreak;
      sections += '"Industry","Number of Employers","Percentage"' + this.lineBreak;
      
      const total = data.industryDistribution.reduce((sum, item) => sum + item.count, 0);
      data.industryDistribution.forEach(item => {
        const percentage = total > 0 ? ((item.count / total) * 100).toFixed(1) : 0;
        sections += `"${item._id || 'Not Specified'}","${item.count}","${percentage}%"${this.lineBreak}`;
      });
    }
    
    // Registration trends
    if (data.registrationTrends) {
      sections += this.lineBreak + '"EMPLOYER REGISTRATION TRENDS"' + this.lineBreak;
      sections += '"Date","Count"' + this.lineBreak;
      
      data.registrationTrends.forEach(trend => {
        const date = this.formatTrendDate(trend._id);
        sections += `"${date}","${trend.count}"${this.lineBreak}`;
      });
    }
    
    return sections;
  }

  generateJobPostingSections(data) {
    let sections = '';
    
    // Status distribution
    if (data.statusDistribution) {
      sections += this.lineBreak + '"JOB STATUS DISTRIBUTION"' + this.lineBreak;
      sections += '"Status","Count","Percentage"' + this.lineBreak;
      
      const total = data.statusDistribution.reduce((sum, item) => sum + item.count, 0);
      data.statusDistribution.forEach(item => {
        const percentage = total > 0 ? ((item.count / total) * 100).toFixed(1) : 0;
        sections += `"${item._id}","${item.count}","${percentage}%"${this.lineBreak}`;
      });
    }
    
    // Department distribution
    if (data.departmentDistribution) {
      sections += this.lineBreak + '"DEPARTMENT DISTRIBUTION"' + this.lineBreak;
      sections += '"Department","Job Count","Percentage"' + this.lineBreak;
      
      const total = data.departmentDistribution.reduce((sum, item) => sum + item.count, 0);
      data.departmentDistribution.forEach(item => {
        const percentage = total > 0 ? ((item.count / total) * 100).toFixed(1) : 0;
        sections += `"${item._id || 'Not Specified'}","${item.count}","${percentage}%"${this.lineBreak}`;
      });
    }
    
    // Salary analytics
    if (data.salaryAnalytics) {
      sections += this.lineBreak + '"SALARY ANALYTICS BY DEPARTMENT"' + this.lineBreak;
      sections += '"Department","Average Salary","Job Count"' + this.lineBreak;
      
      data.salaryAnalytics.forEach(item => {
        const avgSalary = item.avgSalary ? `₱${item.avgSalary.toLocaleString()}` : 'N/A';
        sections += `"${item._id || 'Not Specified'}","${avgSalary}","${item.jobCount || 0}"${this.lineBreak}`;
      });
    }
    
    // Success rates
    if (data.successRates) {
      sections += this.lineBreak + '"JOB SUCCESS RATES BY DEPARTMENT"' + this.lineBreak;
      sections += '"Department","Total Jobs","Total Applications","Total Hired","Success Rate","Avg Applications per Job"' + this.lineBreak;
      
      data.successRates.forEach(item => {
        const successRate = item.successRate ? `${item.successRate.toFixed(1)}%` : '0%';
        const avgApps = item.avgApplicationsPerJob ? item.avgApplicationsPerJob.toFixed(1) : '0';
        sections += `"${item._id || 'Not Specified'}","${item.totalJobs || 0}","${item.totalApplications || 0}","${item.totalHired || 0}","${successRate}","${avgApps}"${this.lineBreak}`;
      });
    }
    
    return sections;
  }

  generateJobDemandSections(data) {
    let sections = '';
    
    // Job demand trends
    if (data.jobDemandTrends) {
      sections += this.lineBreak + '"JOB DEMAND TRENDS"' + this.lineBreak;
      sections += '"Job Title","Department","Total Postings","Total Applications","Avg Applications per Job"' + this.lineBreak;
      
      data.jobDemandTrends.forEach(item => {
        const avgApps = item.avgApplicationsPerJob ? item.avgApplicationsPerJob.toFixed(1) : '0';
        sections += `"${item._id?.title || 'Not Specified'}","${item._id?.department || 'Not Specified'}","${item.totalPostings || 0}","${item.totalApplications || 0}","${avgApps}"${this.lineBreak}`;
      });
    }
    
    // Skills trends
    if (data.skillsTrends) {
      sections += this.lineBreak + '"TOP SKILLS IN DEMAND"' + this.lineBreak;
      sections += '"Rank","Skill","Demand Count"' + this.lineBreak;
      
      data.skillsTrends.forEach((item, index) => {
        sections += `"${index + 1}","${item._id}","${item.count}"${this.lineBreak}`;
      });
    }
    
    // Salary analytics
    if (data.salaryAnalytics) {
      sections += this.lineBreak + '"SALARY ANALYTICS BY JOB TITLE"' + this.lineBreak;
      sections += '"Job Title","Average Salary","Min Salary","Max Salary","Job Count"' + this.lineBreak;
      
      data.salaryAnalytics.forEach(item => {
        const avgSalary = item.avgSalary ? `₱${item.avgSalary.toLocaleString()}` : 'N/A';
        const minSalary = item.minSalary ? `₱${item.minSalary.toLocaleString()}` : 'N/A';
        const maxSalary = item.maxSalary ? `₱${item.maxSalary.toLocaleString()}` : 'N/A';
        sections += `"${item._id || 'Not Specified'}","${avgSalary}","${minSalary}","${maxSalary}","${item.jobCount || 0}"${this.lineBreak}`;
      });
    }
    
    // Industry trends
    if (data.industryTrends) {
      sections += this.lineBreak + '"INDUSTRY JOB TRENDS"' + this.lineBreak;
      sections += '"Industry/Department","Job Count","Market Share"' + this.lineBreak;
      
      const total = data.industryTrends.reduce((sum, item) => sum + item.count, 0);
      data.industryTrends.forEach(item => {
        const percentage = total > 0 ? ((item.count / total) * 100).toFixed(1) : 0;
        sections += `"${item._id || 'Not Specified'}","${item.count}","${percentage}%"${this.lineBreak}`;
      });
    }
    
    return sections;
  }

  generateDetailsSection(details) {
    if (!details || details.length === 0) return '';
    
    let section = '"DETAILED DATA"' + this.lineBreak;
    
    // Get headers from first record
    const headers = Object.keys(details[0]);
    const headerRow = headers.map(header => `"${this.formatLabel(header)}"`).join(this.delimiter);
    section += headerRow + this.lineBreak;
    
    // Add data rows (limit to 1000 records for CSV performance)
    const maxRecords = Math.min(details.length, 1000);
    for (let i = 0; i < maxRecords; i++) {
      const row = details[i];
      const dataRow = headers.map(header => {
        const value = this.formatCellValue(row[header]);
        return `"${String(value).replace(/"/g, '""')}"`;  // Escape quotes in CSV
      }).join(this.delimiter);
      section += dataRow + this.lineBreak;
    }
    
    if (details.length > maxRecords) {
      section += this.lineBreak + `"Note: Showing first ${maxRecords} of ${details.length} records"` + this.lineBreak;
    }
    
    return section;
  }

  generateBulkReportsCSV(allReportsData) {
    let csvContent = '';
    
    // Header
    csvContent += '"PESO - Public Employment Service Office"' + this.lineBreak;
    csvContent += '"Comprehensive Reports Export"' + this.lineBreak;
    csvContent += `"Generated: ${new Date(allReportsData.metadata.generatedAt).toLocaleString()}"${this.lineBreak}`;
    csvContent += `"Date Range: ${allReportsData.metadata.dateRange}"${this.lineBreak}`;
    csvContent += `"Total Reports: ${allReportsData.metadata.totalReports}"${this.lineBreak}`;
    csvContent += this.lineBreak;
    
    // Reports overview
    csvContent += '"REPORTS OVERVIEW"' + this.lineBreak;
    csvContent += '"#","Report Name","Report Type","Category","Status"' + this.lineBreak;
    
    allReportsData.reports.forEach((report, index) => {
      const reportName = this.getReportDisplayName(report.reportType);
      const category = this.getReportCategory(report.reportType);
      csvContent += `"${index + 1}","${reportName}","${report.reportType}","${category}","Generated"${this.lineBreak}`;
    });
    
    // Individual report summaries
    allReportsData.reports.forEach((report, index) => {
      csvContent += this.lineBreak + this.lineBreak;
      csvContent += `"=== REPORT ${index + 1}: ${this.getReportDisplayName(report.reportType).toUpperCase()} ==="${this.lineBreak}`;
      
      if (report.data && report.data.summary) {
        csvContent += this.lineBreak + '"Summary Metrics"' + this.lineBreak;
        csvContent += '"Metric","Value"' + this.lineBreak;
        
        Object.entries(report.data.summary).forEach(([key, value]) => {
          const formattedKey = this.formatLabel(key);
          const formattedValue = this.formatValue(value);
          csvContent += `"${formattedKey}","${formattedValue}"${this.lineBreak}`;
        });
      }
    });
    
    return Buffer.from(csvContent, 'utf8');
  }

  formatTrendDate(dateId) {
    if (dateId.year && dateId.month && dateId.day) {
      return `${dateId.year}-${String(dateId.month).padStart(2, '0')}-${String(dateId.day).padStart(2, '0')}`;
    } else if (dateId.year && dateId.month) {
      return `${dateId.year}-${String(dateId.month).padStart(2, '0')}`;
    } else if (dateId.year) {
      return String(dateId.year);
    }
    return 'Unknown';
  }

  formatLabel(key) {
    return key
      .replace(/([A-Z])/g, ' $1')
      .replace(/^./, str => str.toUpperCase())
      .replace(/([a-z])([A-Z])/g, '$1 $2')
      .trim();
  }

  formatValue(value) {
    if (typeof value === 'number') {
      return value.toLocaleString();
    }
    if (typeof value === 'boolean') {
      return value ? 'Yes' : 'No';
    }
    if (typeof value === 'object' && value !== null) {
      if (Array.isArray(value)) {
        return `${value.length} items`;
      }
      return JSON.stringify(value);
    }
    return String(value);
  }

  formatCellValue(value) {
    if (value === null || value === undefined) {
      return 'N/A';
    }
    if (typeof value === 'boolean') {
      return value ? 'Yes' : 'No';
    }
    if (typeof value === 'number') {
      return value.toLocaleString();
    }
    if (typeof value === 'object') {
      if (value instanceof Date) {
        return value.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
      }
      if (Array.isArray(value)) {
        return `${value.length} items`;
      }
      const str = JSON.stringify(value);
      return str.length > 100 ? str.substring(0, 97) + '...' : str;
    }
    const str = String(value);
    return str.length > 200 ? str.substring(0, 197) + '...' : str;
  }

  getReportDisplayName(reportType) {
    const displayNames = {
      'registered-jobseekers': 'Registered Jobseekers Report',
      'employers-companies': 'Employers/Companies Report',
      'job-postings': 'Job Postings Report',
      'job-demand-analytics': 'Job Demand Analytics Report'
    };
    
    return displayNames[reportType] || reportType.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
  }

  getReportCategory(reportType) {
    const categories = {
      'registered-jobseekers': 'Jobseekers',
      'employers-companies': 'Employers',
      'job-postings': 'Jobs',
      'job-demand-analytics': 'Jobs'
    };
    return categories[reportType] || 'General';
  }
}

module.exports = new CSVReportService();
