let XLSX;
try {
  XLSX = require('xlsx');
} catch (error) {  XLSX = null;
}

class XLSXReportService {
  constructor() {
    this.defaultStyles = {
      header: {
        font: { bold: true, color: { rgb: "FFFFFF" } },
        fill: { fgColor: { rgb: "2563EB" } },
        alignment: { horizontal: "center", vertical: "center" }
      },
      subHeader: {
        font: { bold: true, color: { rgb: "374151" } },
        fill: { fgColor: { rgb: "F3F4F6" } },
        alignment: { horizontal: "left", vertical: "center" }
      },
      data: {
        font: { color: { rgb: "374151" } },
        alignment: { horizontal: "left", vertical: "center" }
      },
      number: {
        font: { color: { rgb: "374151" } },
        alignment: { horizontal: "right", vertical: "center" },
        numFmt: "#,##0"
      },
      currency: {
        font: { color: { rgb: "374151" } },
        alignment: { horizontal: "right", vertical: "center" },
        numFmt: "$#,##0.00"
      }
    };
  }

  generateReportXLSX(reportData, reportName = 'Report') {
    if (!XLSX) {
      throw new Error('XLSX library not available. Please install it with: npm install xlsx');
    }
    
    const workbook = XLSX.utils.book_new();
    const reportType = reportData.reportMetadata.reportType;
    
    // Create summary sheet
    this.addSummarySheet(workbook, reportData, reportName);
    
    // Add report-specific sheets based on report type
    switch (reportType) {
      case 'registered-jobseekers':
        this.addJobseekerSpecificSheets(workbook, reportData);
        break;
      case 'employers-companies':
        this.addEmployerSpecificSheets(workbook, reportData);
        break;
      case 'job-postings':
        this.addJobPostingSpecificSheets(workbook, reportData);
        break;
      case 'job-demand-analytics':
        this.addJobDemandSpecificSheets(workbook, reportData);
        break;
    }
    
    // Create detailed data sheet if available
    if (reportData.data.details && reportData.data.details.length > 0) {
      this.addDetailsSheet(workbook, reportData.data.details, 'Detailed Data');
    }
    
    // Add metadata sheet
    this.addMetadataSheet(workbook, reportData.reportMetadata);
    
    return XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' });
  }

  addSummarySheet(workbook, reportData, reportName) {
    const summaryData = [];
    
    // Title row with organization name
    summaryData.push(['PESO - Public Employment Service Office']);
    summaryData.push([reportName]);
    summaryData.push([]); // Empty row
    
    // Report info in two columns
    summaryData.push(['Report Information', '']);
    summaryData.push(['Generated:', new Date(reportData.reportMetadata.generatedAt).toLocaleString()]);
    summaryData.push(['Date Range:', `${reportData.reportMetadata.startDate} to ${reportData.reportMetadata.endDate}`]);
    summaryData.push(['Generated By:', reportData.reportMetadata.generatedBy]);
    summaryData.push(['Format:', reportData.reportMetadata.format.toUpperCase()]);
    summaryData.push([]); // Empty row
    
    // Summary metrics in organized columns
    if (reportData.data.summary) {
      summaryData.push(['Key Metrics', '', '', '']);
      summaryData.push([]); // Empty row
      
      // Organize metrics in 2 columns for better readability
      const entries = Object.entries(reportData.data.summary);
      const midPoint = Math.ceil(entries.length / 2);
      
      summaryData.push(['Metric', 'Value', '', 'Metric', 'Value']);
      
      for (let i = 0; i < midPoint; i++) {
        const [key1, value1] = entries[i];
        const formattedKey1 = this.formatLabel(key1);
        const formattedValue1 = this.formatValue(value1);
        
        if (i + midPoint < entries.length) {
          const [key2, value2] = entries[i + midPoint];
          const formattedKey2 = this.formatLabel(key2);
          const formattedValue2 = this.formatValue(value2);
          summaryData.push([formattedKey1, formattedValue1, '', formattedKey2, formattedValue2]);
        } else {
          summaryData.push([formattedKey1, formattedValue1, '', '', '']);
        }
      }
    }
    
    const worksheet = XLSX.utils.aoa_to_sheet(summaryData);
    
    // Set column widths for better layout
    worksheet['!cols'] = [
      { width: 30 }, // First metric name
      { width: 20 }, // First value
      { width: 3 },  // Spacer
      { width: 30 }, // Second metric name
      { width: 20 }  // Second value
    ];
    
    // Apply basic styling
    this.applyBasicStyling(worksheet, summaryData.length);
    
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Summary');
  }

  addDetailsSheet(workbook, details, sheetName) {
    if (!details || details.length === 0) return;
    
    // Get proper headers based on data type (matching PDF logic)
    const properHeaders = this.getProperHeaders(details[0]);
    const detailsData = [];
    
    // Add title row with styling
    detailsData.push([sheetName]);
    detailsData.push([]); // Empty row for spacing
    
    // Add headers with formatting
    detailsData.push(properHeaders.map(header => header.label));
    
    // Add data rows with proper formatting
    details.forEach((row, index) => {
      const dataRow = properHeaders.map(header => {
        const value = this.extractCellValue(row, header.key);
        return this.formatCellValue(value);
      });
      detailsData.push(dataRow);
    });
    
    // Add spacing and summary row at bottom
    detailsData.push([]);
    detailsData.push([`Total Records: ${details.length}`, '', '', `Last Updated: ${new Date().toLocaleDateString()}`]);
    
    const worksheet = XLSX.utils.aoa_to_sheet(detailsData);
    
    // Smart column width calculation with better spacing
    const colWidths = properHeaders.map((header, index) => {
      const headerLength = header.label.length;
      const maxContentLength = Math.max(
        ...details.slice(0, 100).map(row => 
          String(this.formatCellValue(this.extractCellValue(row, header.key))).length
        )
      );
      // Add padding for better readability
      return {
        width: Math.min(Math.max(headerLength + 2, maxContentLength + 2, 15), 60)
      };
    });
    worksheet['!cols'] = colWidths;
    
    // Set row heights for better spacing
    worksheet['!rows'] = [
      { hpt: 25 }, // Title row
      { hpt: 10 }, // Empty row
      { hpt: 22 }  // Header row
    ];
    
    // Apply styling and freeze panes
    this.applyBasicStyling(worksheet, detailsData.length);
    
    // Freeze header row (row 3 since we have title and empty row)
    worksheet['!freeze'] = { xSplit: 0, ySplit: 3 };
    
    XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
  }

  addTrendsSheet(workbook, trends, sheetName) {
    if (!trends || trends.length === 0) return;
    
    const trendsData = [];
    
    // Headers based on trend data structure
    if (trends[0]._id) {
      // Handle aggregated trend data
      trendsData.push(['Date', 'Category', 'Count']);
      
      trends.forEach(trend => {
        let dateStr = '';
        if (trend._id.year && trend._id.month && trend._id.day) {
          dateStr = `${trend._id.year}-${String(trend._id.month).padStart(2, '0')}-${String(trend._id.day).padStart(2, '0')}`;
        } else if (trend._id.year && trend._id.month) {
          dateStr = `${trend._id.year}-${String(trend._id.month).padStart(2, '0')}`;
        }
        
        const category = trend._id.role || trend._id.status || 'N/A';
        trendsData.push([dateStr, category, trend.count]);
      });
    } else {
      // Handle simple array data
      trendsData.push(['Index', 'Value']);
      trends.forEach((item, index) => {
        trendsData.push([index + 1, JSON.stringify(item)]);
      });
    }
    
    const worksheet = XLSX.utils.aoa_to_sheet(trendsData);
    
    // Set column widths
    worksheet['!cols'] = [
      { width: 15 }, // Date
      { width: 20 }, // Category
      { width: 10 }  // Count
    ];
    
    this.applyBasicStyling(worksheet, trendsData.length);
    
    XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
  }

  addMetadataSheet(workbook, metadata) {
    const metadataArray = [];
    
    metadataArray.push(['Report Metadata']);
    metadataArray.push([]); // Empty row
    
    Object.entries(metadata).forEach(([key, value]) => {
      const formattedKey = this.formatLabel(key);
      let formattedValue = value;
      
      if (key.includes('Date') && value) {
        formattedValue = new Date(value).toLocaleString();
      } else if (typeof value === 'object') {
        formattedValue = JSON.stringify(value);
      }
      
      metadataArray.push([formattedKey, formattedValue]);
    });
    
    const worksheet = XLSX.utils.aoa_to_sheet(metadataArray);
    
    worksheet['!cols'] = [
      { width: 20 },
      { width: 30 }
    ];
    
    this.applyBasicStyling(worksheet, metadataArray.length);
    
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Metadata');
  }

  generateBulkReportsXLSX(allReportsData) {
    if (!XLSX) {
      throw new Error('XLSX library not available. Please install it with: npm install xlsx');
    }
    
    const workbook = XLSX.utils.book_new();
    
    // Create overview sheet
    this.addOverviewSheet(workbook, allReportsData);
    
    // Create individual sheets for each report
    allReportsData.reports.forEach((report, index) => {
      const reportName = this.getReportDisplayName(report.reportType);
      const sheetName = `${index + 1}. ${reportName}`.substring(0, 31); // Excel sheet name limit
      
      this.addIndividualReportSheet(workbook, report, sheetName);
    });
    
    return XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' });
  }

  addOverviewSheet(workbook, allReportsData) {
    const overviewData = [];
    
    // Title and organization
    overviewData.push(['PESO - Public Employment Service Office']);
    overviewData.push(['Comprehensive Reports Overview']);
    overviewData.push([]);
    
    // Metadata in organized layout
    overviewData.push(['Report Information', '', 'Statistics', '']);
    overviewData.push(['Generated:', new Date(allReportsData.metadata.generatedAt).toLocaleString(), 'Total Reports:', allReportsData.metadata.totalReports]);
    overviewData.push(['Date Range:', allReportsData.metadata.dateRange, 'Failed Reports:', allReportsData.metadata.failedReports || 0]);
    overviewData.push(['Format:', 'Excel Workbook', 'Success Rate:', `${((1 - (allReportsData.metadata.failedReports || 0) / allReportsData.metadata.totalReports) * 100).toFixed(1)}%`]);
    overviewData.push([]);
    
    // Reports list with enhanced columns
    overviewData.push(['#', 'Report Name', 'Report Type', 'Category', 'Status']);
    
    allReportsData.reports.forEach((report, index) => {
      const reportName = this.getReportDisplayName(report.reportType);
      const category = this.getReportCategory(report.reportType);
      overviewData.push([
        index + 1,
        reportName,
        report.reportType,
        category,
        '✓ Generated'
      ]);
    });
    
    // Add summary
    overviewData.push([]);
    overviewData.push(['Summary', '', '', '', '']);
    overviewData.push(['Total Sheets:', allReportsData.reports.length + 1, '', 'Status:', 'Complete']);
    
    const worksheet = XLSX.utils.aoa_to_sheet(overviewData);
    
    worksheet['!cols'] = [
      { width: 5 },  // Index
      { width: 35 }, // Name
      { width: 25 }, // Type
      { width: 20 }, // Category
      { width: 15 }  // Status
    ];
    
    this.applyBasicStyling(worksheet, overviewData.length);
    
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Overview');
  }

  getReportCategory(reportType) {
    const categories = {
      'registered-jobseekers': 'Jobseekers',
      'employers-companies': 'Employers',
      'job-postings': 'Jobs',
      'job-demand-analytics': 'Jobs'
    };
    return categories[reportType] || 'General';
  }

  addIndividualReportSheet(workbook, report, sheetName) {
    const reportData = [];
    
    // Report title and metadata
    const reportDisplayName = this.getReportDisplayName(report.reportType);
    reportData.push([reportDisplayName]);
    reportData.push([`Report Type: ${report.reportType}`]);
    reportData.push([]);
    
    // Summary data in organized columns
    if (report.data && report.data.summary) {
      reportData.push(['Executive Summary']);
      reportData.push([]);
      
      const entries = Object.entries(report.data.summary);
      const midPoint = Math.ceil(entries.length / 2);
      
      reportData.push(['Metric', 'Value', '', 'Metric', 'Value']);
      
      for (let i = 0; i < midPoint; i++) {
        const [key1, value1] = entries[i];
        if (i + midPoint < entries.length) {
          const [key2, value2] = entries[i + midPoint];
          reportData.push([
            this.formatLabel(key1), 
            this.formatValue(value1), 
            '', 
            this.formatLabel(key2), 
            this.formatValue(value2)
          ]);
        } else {
          reportData.push([this.formatLabel(key1), this.formatValue(value1), '', '', '']);
        }
      }
      
      reportData.push([]);
      reportData.push([]);
    }
    
    // Detailed data with better organization
    if (report.data && report.data.details && report.data.details.length > 0) {
      const maxRecords = 500; // Increased limit
      reportData.push([`Detailed Data (Showing ${Math.min(report.data.details.length, maxRecords)} of ${report.data.details.length} records)`]);
      reportData.push([]);
      
      const details = report.data.details.slice(0, maxRecords);
      const headers = Object.keys(details[0]);
      
      // Add headers
      reportData.push(headers.map(h => this.formatLabel(h)));
      
      // Add data rows
      details.forEach(row => {
        const dataRow = headers.map(header => this.formatCellValue(row[header]));
        reportData.push(dataRow);
      });
      
      // Add summary footer
      reportData.push([]);
      reportData.push([`Total Records: ${report.data.details.length}`]);
      if (report.data.details.length > maxRecords) {
        reportData.push([`Note: Showing first ${maxRecords} records for performance`]);
      }
    }
    
    const worksheet = XLSX.utils.aoa_to_sheet(reportData);
    
    // Smart column sizing
    const maxCols = Math.max(...reportData.map(row => row.length));
    const colWidths = [];
    for (let i = 0; i < maxCols; i++) {
      const columnData = reportData.map(row => row[i] || '');
      const maxLength = Math.max(...columnData.map(cell => String(cell).length));
      colWidths.push({ width: Math.min(Math.max(maxLength, 12), 50) });
    }
    worksheet['!cols'] = colWidths;
    
    this.applyBasicStyling(worksheet, reportData.length);
    
    XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
  }

  applyBasicStyling(worksheet, rowCount) {
    // Note: Basic XLSX.js has limited styling capabilities
    // For advanced styling, consider using exceljs or xlsx-style
    
    // Set row heights for headers
    if (!worksheet['!rows']) worksheet['!rows'] = [];
    
    // Make first row (title) taller
    worksheet['!rows'][0] = { hpt: 25 };
    
    // Auto-filter for data tables (if applicable)
    if (rowCount > 2) {
      const range = XLSX.utils.decode_range(worksheet['!ref']);
      if (range.e.r > 1) {
        worksheet['!autofilter'] = { ref: worksheet['!ref'] };
      }
    }
  }

  formatLabel(key) {
    // Convert camelCase to Title Case with proper spacing
    return key
      .replace(/([A-Z])/g, ' $1')
      .replace(/^./, str => str.toUpperCase())
      .replace(/([a-z])([A-Z])/g, '$1 $2')
      .trim();
  }

  formatValue(value) {
    if (typeof value === 'number') {
      return value;
    }
    if (typeof value === 'boolean') {
      return value ? 'Yes' : 'No';
    }
    if (typeof value === 'object' && value !== null) {
      if (Array.isArray(value)) {
        return `${value.length} items`;
      }
      return JSON.stringify(value);
    }
    return String(value);
  }

  formatCellValue(value) {
    if (value === null || value === undefined) {
      return 'N/A';
    }
    if (typeof value === 'boolean') {
      return value ? 'Yes' : 'No';
    }
    if (typeof value === 'number') {
      return value;
    }
    if (typeof value === 'object') {
      if (value instanceof Date) {
        return value.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
      }
      if (Array.isArray(value)) {
        return `${value.length} items`;
      }
      const str = JSON.stringify(value);
      return str.length > 50 ? str.substring(0, 47) + '...' : str;
    }
    const str = String(value);
    return str.length > 100 ? str.substring(0, 97) + '...' : str;
  }

  getProperHeaders(sampleItem) {
    // Define proper headers based on the data structure - matching PDF logic
    if (sampleItem.title && sampleItem.totalApplications !== undefined) {
      // Job demand analytics data - has title and totalApplications
      return [
        { key: 'companyName', label: 'Company Name' },
        { key: 'title', label: 'Job Title' },
        { key: 'totalApplications', label: 'Total Applications' }
      ];
    } else if (sampleItem.title && (sampleItem.department !== undefined || sampleItem.salary !== undefined || sampleItem.status !== undefined)) {
      // Job data - has title and job-specific fields
      return [
        { key: 'title', label: 'Job Title' },
        { key: 'companyName', label: 'Company' },
        { key: 'department', label: 'Department' },
        { key: 'status', label: 'Status' },
        { key: 'salary', label: 'Salary' },
        { key: 'createdAt', label: 'Posted Date' }
      ];
    } else if (sampleItem.firstName || sampleItem.lastName) {
      // JobSeeker data
      return [
        { key: 'email', label: 'Email' },
        { key: 'firstName', label: 'First Name' },
        { key: 'lastName', label: 'Last Name' },
        { key: 'phoneNumber', label: 'Phone Number' },
        { key: 'dateOfBirth', label: 'Birthday' },
        { key: 'age', label: 'Age' },
        { key: 'isActive', label: 'Active' },
        { key: 'createdAt', label: 'Registration Date' }
      ];
    } else if (sampleItem.companyName && (sampleItem.industry !== undefined || sampleItem.accountStatus !== undefined)) {
      // Employer data - has companyName and employer-specific fields
      return [
        { key: 'email', label: 'Email' },
        { key: 'companyName', label: 'Company Name' },
        { key: 'industry', label: 'Industry' },
        { key: 'accountStatus', label: 'Status' },
        { key: 'createdAt', label: 'Registration Date' }
      ];
    } else {
      // Generic fallback
      const keys = Object.keys(sampleItem).filter(key => 
        !key.startsWith('_') && 
        key !== '__v' && 
        typeof sampleItem[key] !== 'object'
      ).slice(0, 6);
      
      return keys.map(key => ({
        key: key,
        label: this.formatLabel(key)
      }));
    }
  }

  extractCellValue(row, key) {
    let value = undefined;
    
    // Handle userId population for employer data
    if (key === 'email' && row.userId) {
      value = row.userId.email;
    } else if (key === 'lastLoginAt' && row.userId) {
      value = row.userId.lastLoginAt;
    } else if (key === 'isActive' && row.userId) {
      value = row.userId.isActive;
    }
    
    // Handle jobseeker-specific fields
    if (key === 'phoneNumber' && row.phoneNumber) {
      value = row.phoneNumber;
    } else if (key === 'dateOfBirth' && row.dateOfBirth) {
      value = row.dateOfBirth;
    } else if (key === 'age' && row.dateOfBirth) {
      // Calculate age from dateOfBirth
      const today = new Date();
      const birthDate = new Date(row.dateOfBirth);
      let age = today.getFullYear() - birthDate.getFullYear();
      const monthDiff = today.getMonth() - birthDate.getMonth();
      if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
        age--;
      }
      value = age;
    }
    
    // Handle direct fields for both employer and job data
    if (key === 'companyName' && row.companyName) {
      value = row.companyName;
    } else if (key === 'industry' && row.industry) {
      value = row.industry;
    } else if (key === 'accountStatus' && row.accountStatus) {
      value = row.accountStatus;
    }
    
    // Handle job-specific fields
    if (key === 'title' && row.title) {
      value = row.title;
    } else if (key === 'department' && row.department) {
      value = row.department;
    } else if (key === 'salary' && row.salary) {
      value = row.salary;
    } else if (key === 'totalApplications' && row.totalApplications !== undefined) {
      value = row.totalApplications;
    }
    
    // If value is still undefined, try to get it directly from row
    if (value === undefined) {
      value = row[key];
    }
    
    return value;
  }

  addJobseekerSpecificSheets(workbook, reportData) {
    const data = reportData.data;
    
    // Remove demographics and registration trends sheets
    // Only keep the main detailed data sheet
  }

  addEmployerSpecificSheets(workbook, reportData) {
    const data = reportData.data;
    
    // Industry distribution sheet
    if (data.industryDistribution) {
      this.addIndustryDistributionSheet(workbook, data.industryDistribution);
    }
    
    // Remove employer registration trends sheet
  }

  addJobPostingSpecificSheets(workbook, reportData) {
    const data = reportData.data;
    
    // Status distribution sheet
    if (data.statusDistribution) {
      this.addStatusDistributionSheet(workbook, data.statusDistribution);
    }
    
    // Department distribution sheet
    if (data.departmentDistribution) {
      this.addDepartmentDistributionSheet(workbook, data.departmentDistribution);
    }
    
    // Salary analytics sheet
    if (data.salaryAnalytics) {
      this.addSalaryAnalyticsSheet(workbook, data.salaryAnalytics);
    }
    
    // Success rates sheet
    if (data.successRates) {
      this.addSuccessRatesSheet(workbook, data.successRates);
    }
    
    // Posting trends sheet
    if (data.postingTrends) {
      this.addTrendsSheet(workbook, data.postingTrends, 'Job Posting Trends');
    }
  }

  addJobDemandSpecificSheets(workbook, reportData) {
    const data = reportData.data;
    
    // Job demand trends sheet
    if (data.jobDemandTrends) {
      this.addJobDemandTrendsSheet(workbook, data.jobDemandTrends);
    }
    
    // Industry trends sheet
    if (data.industryTrends) {
      this.addIndustryTrendsSheet(workbook, data.industryTrends);
    }
  }

  addDemographicsSheet(workbook, demographics) {
    const demographicsData = [];
    
    demographicsData.push(['Jobseeker Demographics Analysis']);
    demographicsData.push([]);
    
    // Gender distribution
    if (demographics.byGender && demographics.byGender.length > 0) {
      demographicsData.push(['Gender Distribution']);
      demographicsData.push(['Gender', 'Count', 'Percentage']);
      
      const totalGender = demographics.byGender.reduce((sum, item) => sum + item.count, 0);
      demographics.byGender.forEach(item => {
        const percentage = totalGender > 0 ? ((item.count / totalGender) * 100).toFixed(1) : 0;
        demographicsData.push([item._id || 'Not Specified', item.count, `${percentage}%`]);
      });
      demographicsData.push([]);
    }
    
    // Age distribution
    if (demographics.byAge && demographics.byAge.length > 0) {
      demographicsData.push(['Age Distribution']);
      demographicsData.push(['Age Group', 'Count', 'Percentage']);
      
      const totalAge = demographics.byAge.reduce((sum, item) => sum + item.count, 0);
      demographics.byAge.forEach(item => {
        const percentage = totalAge > 0 ? ((item.count / totalAge) * 100).toFixed(1) : 0;
        demographicsData.push([item._id, item.count, `${percentage}%`]);
      });
    }
    
    const worksheet = XLSX.utils.aoa_to_sheet(demographicsData);
    worksheet['!cols'] = [{ width: 25 }, { width: 15 }, { width: 15 }];
    this.applyBasicStyling(worksheet, demographicsData.length);
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Demographics');
  }

  addIndustryDistributionSheet(workbook, industryData) {
    const industrySheetData = [];
    
    industrySheetData.push(['Industry Distribution Analysis']);
    industrySheetData.push([]);
    industrySheetData.push(['Industry', 'Number of Employers', 'Percentage']);
    
    const total = industryData.reduce((sum, item) => sum + item.count, 0);
    industryData.forEach(item => {
      const percentage = total > 0 ? ((item.count / total) * 100).toFixed(1) : 0;
      industrySheetData.push([item._id || 'Not Specified', item.count, `${percentage}%`]);
    });
    
    industrySheetData.push([]);
    industrySheetData.push(['Total Industries', industryData.length, '100%']);
    
    const worksheet = XLSX.utils.aoa_to_sheet(industrySheetData);
    worksheet['!cols'] = [{ width: 30 }, { width: 20 }, { width: 15 }];
    this.applyBasicStyling(worksheet, industrySheetData.length);
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Industry Distribution');
  }

  addStatusDistributionSheet(workbook, statusData) {
    const statusSheetData = [];
    
    statusSheetData.push(['Job Status Distribution']);
    statusSheetData.push([]);
    statusSheetData.push(['Status', 'Count', 'Percentage']);
    
    const total = statusData.reduce((sum, item) => sum + item.count, 0);
    statusData.forEach(item => {
      const percentage = total > 0 ? ((item.count / total) * 100).toFixed(1) : 0;
      statusSheetData.push([item._id, item.count, `${percentage}%`]);
    });
    
    const worksheet = XLSX.utils.aoa_to_sheet(statusSheetData);
    worksheet['!cols'] = [{ width: 20 }, { width: 15 }, { width: 15 }];
    this.applyBasicStyling(worksheet, statusSheetData.length);
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Job Status');
  }

  addDepartmentDistributionSheet(workbook, departmentData) {
    const deptSheetData = [];
    
    deptSheetData.push(['Department Distribution']);
    deptSheetData.push([]);
    deptSheetData.push(['Department', 'Job Count', 'Percentage']);
    
    const total = departmentData.reduce((sum, item) => sum + item.count, 0);
    departmentData.forEach(item => {
      const percentage = total > 0 ? ((item.count / total) * 100).toFixed(1) : 0;
      deptSheetData.push([item._id || 'Not Specified', item.count, `${percentage}%`]);
    });
    
    const worksheet = XLSX.utils.aoa_to_sheet(deptSheetData);
    worksheet['!cols'] = [{ width: 25 }, { width: 15 }, { width: 15 }];
    this.applyBasicStyling(worksheet, deptSheetData.length);
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Departments');
  }

  addSalaryAnalyticsSheet(workbook, salaryData) {
    const salarySheetData = [];
    
    salarySheetData.push(['Salary Analytics by Department']);
    salarySheetData.push([]);
    salarySheetData.push(['Department', 'Average Salary', 'Job Count', 'Salary Range']);
    
    salaryData.forEach(item => {
      const avgSalary = item.avgSalary ? `₱${item.avgSalary.toLocaleString()}` : 'N/A';
      const salaryRange = item.minSalary && item.maxSalary ? 
        `₱${item.minSalary.toLocaleString()} - ₱${item.maxSalary.toLocaleString()}` : 'N/A';
      salarySheetData.push([item._id || 'Not Specified', avgSalary, item.jobCount || 0, salaryRange]);
    });
    
    const worksheet = XLSX.utils.aoa_to_sheet(salarySheetData);
    worksheet['!cols'] = [{ width: 25 }, { width: 18 }, { width: 15 }, { width: 25 }];
    this.applyBasicStyling(worksheet, salarySheetData.length);
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Salary Analytics');
  }

  addSuccessRatesSheet(workbook, successData) {
    const successSheetData = [];
    
    successSheetData.push(['Job Success Rates by Department']);
    successSheetData.push([]);
    successSheetData.push(['Department', 'Total Jobs', 'Total Applications', 'Total Hired', 'Success Rate', 'Avg Applications/Job']);
    
    successData.forEach(item => {
      const successRate = item.successRate ? `${item.successRate.toFixed(1)}%` : '0%';
      const avgApps = item.avgApplicationsPerJob ? item.avgApplicationsPerJob.toFixed(1) : '0';
      successSheetData.push([
        item._id || 'Not Specified',
        item.totalJobs || 0,
        item.totalApplications || 0,
        item.totalHired || 0,
        successRate,
        avgApps
      ]);
    });
    
    const worksheet = XLSX.utils.aoa_to_sheet(successSheetData);
    worksheet['!cols'] = [{ width: 25 }, { width: 12 }, { width: 18 }, { width: 12 }, { width: 15 }, { width: 20 }];
    this.applyBasicStyling(worksheet, successSheetData.length);
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Success Rates');
  }

  addJobDemandTrendsSheet(workbook, demandData) {
    const demandSheetData = [];
    
    demandSheetData.push(['Job Demand Trends']);
    demandSheetData.push([]);
    demandSheetData.push(['Job Title', 'Department', 'Total Postings', 'Total Applications', 'Avg Applications/Job']);
    
    demandData.forEach(item => {
      const avgApps = item.avgApplicationsPerJob ? item.avgApplicationsPerJob.toFixed(1) : '0';
      demandSheetData.push([
        item._id?.title || 'Not Specified',
        item._id?.department || 'Not Specified',
        item.totalPostings || 0,
        item.totalApplications || 0,
        avgApps
      ]);
    });
    
    const worksheet = XLSX.utils.aoa_to_sheet(demandSheetData);
    worksheet['!cols'] = [{ width: 30 }, { width: 20 }, { width: 15 }, { width: 18 }, { width: 20 }];
    this.applyBasicStyling(worksheet, demandSheetData.length);
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Job Demand');
  }

  addSkillsTrendsSheet(workbook, skillsData) {
    const skillsSheetData = [];
    
    skillsSheetData.push(['Top Skills in Demand']);
    skillsSheetData.push([]);
    skillsSheetData.push(['Skill', 'Demand Count', 'Rank']);
    
    skillsData.forEach((item, index) => {
      skillsSheetData.push([item._id, item.count, index + 1]);
    });
    
    const worksheet = XLSX.utils.aoa_to_sheet(skillsSheetData);
    worksheet['!cols'] = [{ width: 25 }, { width: 15 }, { width: 10 }];
    this.applyBasicStyling(worksheet, skillsSheetData.length);
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Skills Trends');
  }

  addIndustryTrendsSheet(workbook, industryData) {
    const industrySheetData = [];
    
    industrySheetData.push(['Industry Job Trends']);
    industrySheetData.push([]);
    industrySheetData.push(['Industry/Department', 'Job Count', 'Market Share']);
    
    const total = industryData.reduce((sum, item) => sum + item.count, 0);
    industryData.forEach(item => {
      const percentage = total > 0 ? ((item.count / total) * 100).toFixed(1) : 0;
      industrySheetData.push([item._id || 'Not Specified', item.count, `${percentage}%`]);
    });
    
    const worksheet = XLSX.utils.aoa_to_sheet(industrySheetData);
    worksheet['!cols'] = [{ width: 30 }, { width: 15 }, { width: 15 }];
    this.applyBasicStyling(worksheet, industrySheetData.length);
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Industry Trends');
  }

  getReportDisplayName(reportType) {
    const displayNames = {
      'registered-jobseekers': 'Registered Jobseekers Report',
      'employers-companies': 'Employers/Companies Report',
      'job-postings': 'Job Postings Report',
      'job-demand-analytics': 'Job Demand Analytics Report'
    };
    
    return displayNames[reportType] || reportType.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
  }
}

module.exports = new XLSXReportService();
